### ISSUE TITLE
Suggest to loosen the dependency on tweepy

### ISSUE THREAD

**Issue by Agnes-U** [New-dev0/TgTwitterStreamer#11]
Hi, your project TgTwitterStreamer(commit id: e2946e41c812e57e110aa1dcd3e872ffb3e6e046) requires "tweepy==4.5.0" in its dependency. After analyzing the source code, we found that the following versions of tweepy can also be suitable, i.e., tweepy 4.6.0, 4.7.0, 4.8.0, since all functions that you directly (6 APIs: tweepy.auth.OAuth1UserHandler.set_access_token, tweepy.api.API.get_user, tweepy.errors.Unauthorized.__init__, tweepy.api.API.__init__, tweepy.auth.OAuthHandler.__init__, tweepy.asynchronous.streaming.AsyncStream.__init__) or indirectly (propagate to 9 tweepy's internal APIs and 8 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on tweepy from "tweepy==4.5.0" to "tweepy>=4.5.0,<=4.8.0". This will improve the applicability of TgTwitterStreamer and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on tweepy?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by New-dev0** [comment]
> May I pull a request to further loosen the dependency on tweepy?

 You can.

> By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

Yes, It will beneficial.
