### ISSUE TITLE
Error: authentication error

### ISSUE THREAD

**Issue by chankitsaini** [New-dev0/TgTwitterStreamer#14]
When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.

**Comment by New-dev0** [comment]
https://github.com/New-dev0/TgTwitterStreamer/commit/90ce3da73a859e6a1e693af9eda43dd0298c0260

**Comment by New-dev0** [comment]
TgTwitterStreamer no longer use twitter api's now.
