### ISSUE TITLE
did twitter streamer not worked on free twitter api?

### ISSUE THREAD

**Issue by zYxDevs** [New-dev0/TgTwitterStreamer#16]
![Screenshot_20230727-000339_Termius](https://github.com/New-dev0/TgTwitterStreamer/assets/45356875/ae437aef-a338-40b9-a8a9-3fc87173b03a)

The basic twitter api access is too expensive:(

**Comment by zYxDevs** [comment]
please integrate to rss-bridge for free twitter api users.

**Comment by New-dev0** [comment]
I have moved to tweeterpy instead of official twitter API, which is based on scrapping twitter web
https://github.com/New-dev0/TgTwitterStreamer/commit/90ce3da73a859e6a1e693af9eda43dd0298c0260
