### ISSUE TITLE
Can anyone help me fix this problem?

### ISSUE THREAD

**Issue by fatratkiller** [New-dev0/TgTwitterStreamer#17]
<img width="566" alt="截圖 2024-06-17 11 48 28" src="https://github.com/New-dev0/TgTwitterStreamer/assets/151895782/6764dfff-6eea-4d38-a499-a4e13774fd2e">
i have input the telegram user id in the env file. is there any problem?

**Comment by New-dev0** [comment]
TgTwitterStreamer and TgtwitterBot are two different repositories.
You have cloned TgtwitterBot

**Comment by New-dev0** [comment]
To install TgTwitterStreamer 
1. `git clone https://github.com/New-dev0/TgTwitterStreamer`
2. `pip3 install -r requirements.txt`
3. Setup the env
4. To start, `python3 bot.py`

**Comment by New-dev0** [comment]
Docs/Readme is currently outdated and all the mandatory variables are

API_ID
API_HASH
BOT_TOKEN
TWITTER_USERNAME
TWITTER_PASSWORD
TO_CHAT
TRACK_USERS

**Comment by fatratkiller** [comment]
thx~ it is strange that the terminal errors although i have input the "usrname" and "password" in env file. Could you figure out?
<img width="562" alt="截圖 2024-06-17 14 35 57" src="https://github.com/New-dev0/TgTwitterStreamer/assets/151895782/2669798d-9616-4478-9768-d4c45fae41aa">

**Comment by New-dev0** [comment]
No, I dont have encountered that issue! maybe something with your `.env` file
Other way is,
you can modify the config file on your local filesystem and directly enter the values
 https://github.com/New-dev0/TgTwitterStreamer/blob/e00e20e9afeb852f9e9e1de59eca42d54e48a8b9/Configs.py#L71
