### ISSUE TITLE
Update deploy on railway template please sir

### ISSUE THREAD

**Issue by bulanbintang69** [New-dev0/TgTwitterStreamer#9]
![IMG_20220813_184955_249](https://user-images.githubusercontent.com/87313549/184492892-1175f01e-c125-4ad4-ac94-453f5f61f723.jpg)

**Comment by IndrajeethY** [comment]
Sad

**Comment by bulanbintang69** [comment]
@TAMILVIP007 Sad to

**Comment by IndrajeethY** [comment]
> @TAMILVIP007 Sad to

Better die
